{% set name = "tfcausalimpact" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/tfcausalimpact-{{ version }}.tar.gz
  sha256: a6131cd519a8108c1b71274e12619a184a15a7223035914d8a1e0af349276b53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flake8
    - isort
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2
    - pandas >=1.3.5,<=2.2.3
    - tensorflow >=2.10
    - tensorflow-probability >=0.18,<=0.25
    - matplotlib-base

test:
  imports:
    - causalimpact
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WillianFuks/tfcausalimpact
  summary: Python version of Google's Causal Impact model on top of Tensorflow Probability.
  dev_url: https://github.com/WillianFuks/tfcausalimpact
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
